const ItensMenu = [
    {
        id: 1,
        icone: 'user-tie',
        title: 'Cargos',
        buttonName: 'Cargo',
        route: 'cargos',
        campo1:'Nome',
        campo2:'Email',
        linkNovo: 'Novo',
        linkEditar: 'Editar',
        linkListar: 'Listar',
        iconLink: 'circle-notch'
    },
    {
        id: 2,
        icone: 'user-friends',
        title: 'Clientes',
        buttonName: 'Cliente',
        route: 'clientes',
        campo1:'Nome',
        campo2:'CPF/CNPJ',
        linkNovo: 'Novo',
        linkEditar: 'Editar',
        linkListar: 'Listar',
        iconLink: 'circle-notch'
    },
    {
        id: 3,
        icone: 'users',
        title: 'Colaboradores',
        buttonName: 'Colaborador',
        route: 'colaboradores',
        campo1:'Nome',
        campo2:'Email',
        linkNovo: 'Novo',
        linkEditar: 'Editar',
        linkListar: 'Listar',
        iconLink: 'circle-notch'
    },
    {
        id: 4,
        icone: 'copy',
        title: 'Documentos',
        buttonName: 'Documento',
        route: 'documentos',
        campo1:'Título',
        campo2:'Código',
        linkNovo: 'Novo',
        linkEditar: 'Editar',
        linkListar: 'Listar',
        iconLink: 'circle-notch'
    },
    {
        id: 5,
        icone: 'microscope',
        title: 'Equipamentos',
        buttonName: 'Equipamento',
        route: 'equipamentos',
        campo1:'Equipamento Próprio',
        campo2:'Equipamento',
        linkNovo: 'Novo',
        linkEditar: 'Editar',
        linkListar: 'Listar',
        iconLink: 'circle-notch'
    },
    {
        id: 6,
        icone: 'dolly-flatbed',
        title: 'Fornecedores',
        buttonName: 'Fornecedor',
        route: 'fornecedores',
        campo1:'Tipo',
        campo2:'CNPJ',
        linkNovo: 'Novo',
        linkEditar: 'Editar',
        linkListar: 'Listar',
        iconLink: 'circle-notch'
    },
    {
        id: 7,
        icone: 'toolbox',
        title: 'Serviços',
        buttonName: 'Serviço',
        route: 'servicos',
        campo1:'Descrição',
        campo2:'Tipo serviço',
        linkNovo: 'Novo',
        linkEditar: 'Editar',
        linkListar: 'Listar',
        iconLink: 'circle-notch'
    },
    {
        id: 8,
        icone: 'building',
        title: 'Setores',
        buttonName: 'Setor',
        route: 'setores',
        campo1:'Setor',
        campo2:'Setor Pai',
        linkNovo: 'Novo',
        linkEditar: 'Editar',
        linkListar: 'Listar',
        iconLink: 'circle-notch'
    },
    {
        id: 9,
        icone: 'user',
        title: 'Usuarios',
        buttonName: 'Usuário',
        route: 'user',
        campo1:'Nome',
        campo2:'Email',
        linkNovo: 'Novo',
        linkEditar: 'Editar',
        linkListar: 'Listar',
        iconLink: 'circle-notch'
    },
];

export default ItensMenu;